# Generated by Django 4.2.14 on 2024-07-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_school_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="here_place_id",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
