# Generated by Django 4.2.14 on 2024-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_school_here_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="here_place_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
