# Generated by Django 4.2.14 on 2024-07-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_school_distance_school_email_school_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="preference",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Sibling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("year_group", models.CharField(max_length=100)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.application",
                    ),
                ),
            ],
        ),
    ]
