# Generated by Django 4.2.14 on 2024-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_application_preference_sibling"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="siblings",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="application",
            name="preference",
            field=models.IntegerField(default=0),
        ),
    ]
