# Generated by Django 4.2.14 on 2024-07-22 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_application_siblings_alter_application_preference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sibling",
        ),
    ]
