# Generated by Django 4.2.14 on 2024-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_delete_sibling"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="preference",
        ),
        migrations.RemoveField(
            model_name="application",
            name="school",
        ),
        migrations.AddField(
            model_name="application",
            name="preferences",
            field=models.JSONField(default=list),
        ),
    ]
