# Generated by Django 4.2.14 on 2024-07-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_application_siblings"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Application Submitted"),
                    ("in_progress", "In Progress"),
                    ("offer_received", "Offer Received"),
                    ("offer_accepted", "Offer Accepted"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
