# Generated by Django 4.2.14 on 2024-08-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="offered_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications_offered",
                to="accounts.school",
            ),
        ),
    ]
